name: test
runs-on: ubuntu-latest
on:
  pull_request:
    branches:
      - main
jobs:
  steps:
    - name: install
      uses: purcell/setup-emacs@master
      with:
        version: 26.1
    - name: test
      needs: setup
      run: make test
    - name: lint
      needs: setup
      run: make lint
