name: test
on:
  pull_request:
    branches:
      - main
jobs:
  setup:
    uses: purcell/setup-emacs@master
    with:
      version: 26.1
  test:
    needs: setup
    run: make test
  lint:
    needs: setup
    run: make lint
