name: test
runs-on: ubuntu-latest
on:
  pull_request:
    branches:
      - main
env:
  PR_COMMIT_SHA: ${{ github.event.client_payload.pull_request.head.sha }}
jobs:
  steps:
    - uses: purcell/setup-emacs@master
      with:
        version: 26.1
    - uses: actions/checkout@v2
      with:
        ref: ${{ env.PR_COMMIT_SHA }}
    - name: test
      needs: setup
      run: make test
    - name: lint
      needs: setup
      run: make lint
