name: test
on:
  pull_request:
    branches:
      - main
env:
  PR_COMMIT_SHA: ${{ github.event.client_payload.pull_request.head.sha }}
jobs:
  test_and_lint:
    name: Test and Lint
    strategy:
      matrix:
        # We need to make sure we are testing at least the earliest and latest versions of
        # Emacs.
        version: ["27.1", "29.1"]
    runs-on: ubuntu-latest
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.version }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.PR_COMMIT_SHA }}
      - name: test
        run: make test
      - name: lint
        run: make lint
